#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# first, run composer req annotations
controllers:
   resource: ../src/Controller/
   type: annotation

hello:
    path: /hello
    defaults: { _controller: 'App\Controller\Hello::Hello' }
